
package com.bigdata.web.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.3
 * Tue Dec 30 17:36:56 CST 2014
 * Generated source version: 3.0.3
 */

@XmlRootElement(name = "hello", namespace = "http://web.bigdata.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hello", namespace = "http://web.bigdata.com/")

public class Hello {

    @XmlElement(name = "user")
    private java.lang.String user;

    public java.lang.String getUser() {
        return this.user;
    }

    public void setUser(java.lang.String newUser)  {
        this.user = newUser;
    }

}

